spring.application.name=cavosh_cafe

spring.datasource.url=jdbc:mysql://localhost:3306/ormtestspring
spring.datasource.username=root
spring.datasource.password=1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

security.jwt.secret-key=7e2f79147c4f8e22b30eb73aee57c5b51b86eb8601a4a5c97322f7d7b518506f